# Generated by Django 5.2.13 on 2026-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interviewexport_id_alter_interviewturn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
