# Generated by Django 5.2.13 on 2026-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_interviewexport_id_alter_interviewturn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
